-- NOVESSA Core persistence schema
-- Repository definition only; this does not claim a remote database is provisioned.

create table if not exists public.novessa_workspaces (
  workspace_id text not null,
  kind text not null check (kind in ('book','sheets')),
  state jsonb not null default '{}'::jsonb,
  version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (workspace_id, kind)
);

create table if not exists public.novessa_events (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  event_kind text not null,
  request_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.novessa_workspaces enable row level security;
alter table public.novessa_events enable row level security;

revoke all on public.novessa_workspaces from anon, authenticated;
revoke all on public.novessa_events from anon, authenticated;
grant all on public.novessa_workspaces to service_role;
grant all on public.novessa_events to service_role;
grant usage, select on sequence public.novessa_events_id_seq to service_role;

create index if not exists novessa_events_workspace_created_idx
  on public.novessa_events (workspace_id, created_at desc);
